hellomake:
	g++ -w -DLOG_TO_STDOUT=1 -ochatserver ../../Util.cpp ../../WebSocketServer.cpp chatServer.cpp \
	-I../../libwebsockets/include ../../libwebsockets/lib/linux_x64/libwebsockets.a \
	-lz -lssl -lcrypto -lm -lpthread


